### PR TITLE
Update spark and scala versions

### PR DESCRIPTION
**Pull request by HarshAgwl**
Updating spark to v2.4.5 and scala to v2.12.11
21 of 21 unit tests in the project passed

### CODE REVIEW

**Comment by ashwanthkumar** [comment]
@HarshAgwl Is there anything else pending on this PR or can we merge it in and cut a release?

**Comment by HarshAgwl** [comment]
> @HarshAgwl Is there anything else pending on this PR or can we merge it in and cut a release?

sparkplug is a dependency of holonet. holonet will use spark 2.4.5 while currently sparkplug is using spark 2.4.0. If this will not cause any issue, it is safe to merge it and release it.

**Comment by ashwanthkumar** [comment]
Try upgrading the version to 2.4.5 and let's try if the Travis build goes
green.

**Comment by HarshAgwl** [comment]
Successfully built with spark 2.4.5. Can merge it now.

**Comment by ashwanthkumar** [comment]
Go for it. Once you merge it. I can cut a release.

**Comment by HarshAgwl** [comment]
I don't have write access to the repo. I can't merge the PR.

**Comment by ashwanthkumar** [comment]
Oops, I did not realise that. Merging this now.

**Pull request merged**
